import type { SearchResultCard } from "../types";

export const SEARCH_RESULT_CARD_SAMPLE: SearchResultCard = {
  videoId: "video-1",
  title: "가족 대화 실전 팁",
  channelName: "마음연구소",
  thumbnailUrl: "https://img.youtube.com/vi/video-1/hqdefault.jpg",
  durationText: "12:34",
  publishedDateText: "2026-03-01",
  viewCount: 10234,
  viewCountText: "10,234",
  subscriberCount: 56789,
  subscriberCountText: "56,789",
  likeCount: 120,
  commentCount: 45,
  channelPublishedDateText: "2021-10-01",
  countryCode: "KR",
  totalVideoCountText: "120",
  subscriptionRateText: "1.5%",
  annualSubscriberGrowthText: "12%",
  uploadsPerWeekText: "2.1",
  channelGrade: "A",
  isShortForm: false,
  hasScript: true,
  isSubscriberPublic: true,
  keywordMatchedTerms: ["가족", "대화"],
  contributionGrade: "A",
  performanceScore: 87.5,
  exposureScore: 74.2,
  isHotVideo: true,
  recommendationReason: "댓글 참여율이 높아 후속 소재 확장 가능성이 큽니다.",
  estimatedRevenueTotalText: "$123",
  vphText: "120",
  badgeLabel: "급상승",
};
